spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/myschema
  application:
    name: taskservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration