# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=taskservice
      - MYSQL_ROOT_PASSWORD=password
